c++ helloworld example application
unikraft/static-pie-apps pull request #4
Opened 2022-05-15 14:51 UTC by huyhoang8398

add c++ helloworld example programs

2022-05-15 14:54 UTC, razvand commented
Please use `Add ...` as part of your commit message.

2022-05-15 14:55 UTC, razvand requested changes

2022-05-15 14:55 UTC, razvand commented on lang/c++/Makefile
> +CC = g++
You should call this `CXX`.

2022-05-15 14:55 UTC, razvand commented on lang/c++/Makefile
> +	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).cpp
I think this is implicit and may be removed.

2022-05-15 14:55 UTC, razvand commented on lang/c++/Makefile
> +
Make `all` and `clean` targets phony.

```
PHONY: all clean
```

2022-05-15 15:01 UTC, huyhoang8398 commented on lang/c++/Makefile
> +
this should be .PHONY: all clean

2022-06-26 14:24 UTC, ouss-ch requested changes

2022-06-26 14:24 UTC, ouss-ch commented on lang/c++/Makefile
> +CXX = g++
using CXX seems to cause undefined reference errors. I tried CC and it seems to work fine.

2022-07-01 16:01 UTC, razvand requested changes
Thanks, @huyhoang8398 . I made some comments.

Apart from those, please:
* Add the `helloworld` executable file to the commit.
* Remove the `C` folder from the commit.

2022-07-01 16:01 UTC, razvand commented on lang/c++/helloworld.cpp
> +  std::cout << "Hello World!";
Use Tab indentation.

2023-01-03 13:51 UTC, razvand approved these changes
Thanks, @huyhoang8398.

Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

2023-01-03 13:51 UTC, merged